 # block (bloco), beam (barra vertical), underline (underline)
cursor_shape beam 

 # controla a espessura da barra e so funciona se o cursor for beam
cursor_beam_thickness 1.5

# tempo que o cursor pisca
cursor_blink_interval 0.5 

# tempo pro cursor parar de piscar (0 nunca para)
cursor_stop_blinking_after 0 

# pro kitty integrar melhor com o shell
shell_integration enabled 

# quantos rastros o cursor vai deixar, 0 desligado, 1 pequeno, 3 suave, 8 bem visivel
cursor_trail 3

# controla a velocidade da animacao (inicio fim) menor eh mais rapido e maior eh mais suave
cursor_trail_decay 0.1 0.4

# remove os 3 botoes max, min, close (deixa a barra minima)
hide_window_decorations yes
# hide_window_decorations titlebar-only -> se vc quiser que apareça os 3 botoes

# configurar o title da janela
window_title t3cl4do

initial_window_width 100c
initial_window_height 40c

font_size 14.0


# BEGIN_KITTY_THEME
# Ayu
include current-theme.conf
# END_KITTY_THEME